-- CREAZIONE DEI RUOLI

CREATE ROLE ROLE_ADMIN;
CREATE ROLE ROLE_DOCTOR;
CREATE ROLE ROLE_NURSE;
CREATE ROLE ROLE_BILLING;
CREATE ROLE ROLE_ANALYST;
CREATE ROLE ROLE_RESEARCHER;

-- DEFINIZIONE DEI PRIVILEGI PER I DIVERSI RUOLI

-- ROLE_ADMIN è quello con i permessi maggiori
-- Tutto su database/schema
GRANT ALL PRIVILEGES ON DATABASE SNOWFLAKE_LEARNING_DB TO ROLE ROLE_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_LEARNING_DB.STAGING TO ROLE ROLE_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_LEARNING_DB.CORE TO ROLE ROLE_ADMIN;
-- Gestione masking policy
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE ROLE_ADMIN;

-- PERMESSI PER IL RUOLO DOCTOR

GRANT USAGE ON DATABASE SNOWFLAKE_LEARNING_DB TO ROLE ROLE_DOCTOR;
-- accesso solo allo schema CORE
GRANT USAGE ON SCHEMA SNOWFLAKE_LEARNING_DB.CORE TO ROLE ROLE_DOCTOR;

GRANT SELECT ON TABLE SNOWFLAKE_LEARNING_DB.CORE.PATIENTS TO ROLE ROLE_DOCTOR;
GRANT SELECT ON TABLE SNOWFLAKE_LEARNING_DB.CORE.HOSPITAL_ADMISSIONS TO ROLE ROLE_DOCTOR;
GRANT SELECT ON TABLE SNOWFLAKE_LEARNING_DB.CORE.PRESCRIPTIONS TO ROLE ROLE_DOCTOR;
GRANT SELECT ON TABLE SNOWFLAKE_LEARNING_DB.CORE.PROCEDURES TO ROLE ROLE_DOCTOR;
GRANT SELECT ON TABLE SNOWFLAKE_LEARNING_DB.CORE.VITAL_SIGNS_CONSOLIDATED TO ROLE ROLE_DOCTOR;

-- PERMESSI PER IL RUOLO INFERMIERE

GRANT USAGE ON DATABASE SNOWFLAKE_LEARNING_DB TO ROLE ROLE_NURSE;
-- accesso solo allo schema CORE
GRANT USAGE ON SCHEMA SNOWFLAKE_LEARNING_DB.CORE TO ROLE ROLE_NURSE;

GRANT SELECT ON TABLE SNOWFLAKE_LEARNING_DB.CORE.PATIENTS TO ROLE ROLE_NURSE;
GRANT SELECT ON TABLE SNOWFLAKE_LEARNING_DB.CORE.HOSPITAL_ADMISSIONS TO ROLE ROLE_NURSE;
GRANT SELECT ON TABLE SNOWFLAKE_LEARNING_DB.CORE.VITAL_SIGNS_CONSOLIDATED TO ROLE ROLE_NURSE;

-- permessi per il ruolo di Amministrativo

GRANT USAGE ON DATABASE SNOWFLAKE_LEARNING_DB TO ROLE ROLE_BILLING;
GRANT USAGE ON SCHEMA SNOWFLAKE_LEARNING_DB.CORE TO ROLE ROLE_BILLING;

GRANT SELECT ON TABLE SNOWFLAKE_LEARNING_DB.CORE.INVOICES TO ROLE ROLE_BILLING;
GRANT SELECT ON TABLE SNOWFLAKE_LEARNING_DB.CORE.PATIENTS TO ROLE ROLE_BILLING;

-- permessi per il ruolo di Analista

GRANT USAGE ON SCHEMA SNOWFLAKE_LEARNING_DB.CORE TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW VW_AVG_COST_PER_ADMISSION TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW VW_OUTCOME_STATS TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW VW_REPARTO_INVOICES_SUMMARY TO ROLE ROLE_ANALYST;


--permessi per il ruolo di Ricercatore

GRANT USAGE ON DATABASE SNOWFLAKE_LEARNING_DB TO ROLE ROLE_RESEARCHER;
GRANT USAGE ON SCHEMA SNOWFLAKE_LEARNING_DB.CORE TO ROLE ROLE_RESEARCHER;

GRANT SELECT ON TABLE SNOWFLAKE_LEARNING_DB.CORE.PATIENTS TO ROLE ROLE_RESEARCHER;
GRANT SELECT ON TABLE SNOWFLAKE_LEARNING_DB.CORE.HOSPITAL_ADMISSIONS TO ROLE ROLE_RESEARCHER;


-- DEFINIZIONE DELLE MASKING POLICY

--GESTIONE DEL CODICE FISCALE

--mascheramento del codice fiscale
CREATE OR REPLACE MASKING POLICY CORE.MASK_CF_POLICY AS
  (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_ADMIN', 'ROLE_DOCTOR') THEN val
    ELSE '**********'
  END
  ;

-- applicazione della policy
ALTER TABLE SNOWFLAKE_LEARNING_DB.CORE.PATIENTS 
  MODIFY COLUMN CF SET MASKING POLICY MASK_CF_POLICY;

--GESTIONE DI NOME E COGNOME

-- creazione della policy
CREATE OR REPLACE MASKING POLICY CORE.MASK_NAME_POLICY AS
  (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_ADMIN', 'ROLE_DOCTOR', 'ROLE_NURSE') THEN val
    ELSE CONCAT(UPPER(LEFT(val,1)), REPEAT('*', LENGTH(val)-1))
  END
  ;
--APPLICAZIONE DELLA POLICY
ALTER TABLE SNOWFLAKE_LEARNING_DB.CORE.PATIENTS 
  MODIFY COLUMN NOME SET MASKING POLICY MASK_NAME_POLICY;

ALTER TABLE SNOWFLAKE_LEARNING_DB.CORE.PATIENTS 
  MODIFY COLUMN COGNOME SET MASKING POLICY MASK_NAME_POLICY;

-- GESTIONE DEI DATI ECONOMICI
--CREAZIONE DELLA POLICY
CREATE OR REPLACE MASKING POLICY MASK_COST_POLICY AS
  (val NUMBER) RETURNS NUMBER ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_ADMIN', 'ROLE_DOCTOR', 'ROLE_BILLING') THEN val
    ELSE NULL
  END;

ALTER TABLE SNOWFLAKE_LEARNING_DB.CORE.HOSPITAL_ADMISSIONS
  MODIFY COLUMN COSTO_TOTALE SET MASKING POLICY MASK_COST_POLICY;